### ISSUE TITLE
Überschriftsgrösse bei Umfragen anpassen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#100]
Könntest du Carlo folgende CSS-Anpassung noch machen? Merci.

Anfrage von Jasmina: Eine kleine Formatierungsanpassung hätte ich noch, falls es nicht ein Riesenaufwand ist. Mit ist bei der Umfrage aufgefallen, dass der als Titel definierte Text kleiner ist als der normale Text, den man zusätzlich bei jeder Frage eingeben kann (die Titel mit den Zahlen sind kleiner als der Text darunter). Das sieht etwas seltsam aus. Ist das schwierig zum Angleichen (Titel mit Nummer gleich gross wie der restliche Text)?
 
https://test.impulskoeniz.ch/processes/liebefeldmitte/f/700/

![Image](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/a79cfde3-6a4a-4409-b8b3-86a6eb5ea7ca)

**Comment by carlobeltrame** [comment]
Ist auf INT und PROD umgesetzt.

**Comment by innosmith** [comment]
Bestens, vielen Dank!
