### ISSUE TITLE
Backup INT vor Pentest

### ISSUE THREAD

**Issue by bsantschi** [decidim-swiss/decidim.swiss#103]

**Comment by Kagemaru** [comment]
Files wurden intern abgelegt

**Comment by carlobeltrame** [comment]
Sollten wir das nicht noch etwas zeitnaher vor dem Pentest machen? Ich hatte mir dafür ursprünglich mal einen Termin nächsten Montagmorgen eingetragen.

**Comment by bsantschi** [comment]
Guter Punkt, danke Carlo. Gerne darfst du am Montag ca. 9:00 Uhr nochmals ein Backup machen.

**Comment by Kagemaru** [comment]
@carlobeltrame Machst du auch ein Backup der Dateien vom S3?

**Comment by carlobeltrame** [comment]
Wüsste nicht wie

**Comment by bsantschi** [comment]
Thomas hat das S3 Backup erstellt.
