### ISSUE TITLE
Terms werden in Mailvorlage nicht übernommen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#105]
Aus dem Emailaustausch Jasmina und Carlo per 01.09.2023:

Hallo Carlo

Ich habe die Terms angepasst, Cache gelöscht, leider übernimmt es die angepassten Übersetzungen nicht, es werden immer noch die fehlerhaften Original-Terms angezeigt (betreffendes Mail im Anhang).

Anthony hat die Terms nochmals kontrolliert, Cache ebenfalls gelöscht, aber auch bei ihn zeigt es in der Willkommens-Mail immer noch die fehlerhaften Terms an.

Könnt ihr euch das detaillierter anschauen, warum die Terms nicht übernommen werden?

Merci vielmals.

Viele Grüsse
Jasmina

Translation Key für Betreff: 
decidim.welcome_notification.default_subject

Translation Key für Textkörper: 
decidim.welcome_notification.default_body

**Comment by innosmith** [comment]
@carlobeltrame : könntest du hierbei bitte rasch helfen? Es gibt negative Rückmeldungen in Köniz, weil wir es nicht schaffen, das Standard Kauderwelsch bei den Willkommens-Emails anzupassen.

**Comment by larsUE** [comment]
@innosmith Das Willkommens-Email lässt sich in den normalen [Plattformeinstellungen](https://impulskoeniz.ch/admin/organization/edit) verfassen und überschreibt m.E. auch die Term-Customizer Version. Habt ihr das angepasst?

**Comment by innosmith** [comment]
@larsUE : ja, das hat Jasmina angepasst. Ich habe jetzt aber gerade gesehen, dass die Checkbox deaktiviert war!

**Comment by larsUE** [comment]
Hab mich eben registriert und diese Nachricht erhalten: 
<img width="904" alt="Bildschirmfoto 2023-09-05 um 11 08 42" src="https://github.com/decidim-swiss/decidim.swiss/assets/60926257/100ebf82-e5d4-4ff6-9965-96f6614ccdc9">

**Comment by innosmith** [comment]
Bei mir funktioniert es jetzt auch, somit schliesse ich das Ticket. Danke für den Support!

**Comment by bsantschi** [comment]
Danke für deine Unterstützung, @larsUE !
