### ISSUE TITLE
500er auf Profilseite

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#107]
Ich kriege auf einem Tab in meinem Profil einen 500er: https://cokreation.winterthur.ch/profiles/lars_kaiser/following
Betrifft alle Profile.

Vermutung 1: Fehlende Übersetzung -> Dann bitte mir den Key geben
Vermutung 2: Crash wegen Zugriff auf verborgene/gelöschte Ressource -> bitte Ressource manuell entfernen.

**Comment by carlobeltrame** [comment]
Es ist ein Bug in einer Anpassung die wir noch von der Quartieridee übernommen hatten... Weiss ehrlich gesagt nicht mehr wofür wir das genau gemacht haben. Dürfte wohl beim Upgrade kaputt gegangen sein.
https://github.com/stadtluzern/decidim-ocl/blob/master/app/cells/decidim_ocl/participatory_processes/process_m_cell.rb#L20

**Comment by larsUE** [comment]
Wenn es von der Quartieridee stammt dann kann das von mir aus gerne rückgerollt werden. Dort hatten wir ja einige Anpassungen, die spezifisch auf den Prozess zugeschnitten waren.

**Comment by Kagemaru** [comment]
Das war die Anpassung für die Default-Bilder der Partizipationsprozesse. Er findet den Pfad auf das Bild nicht, ich schaue mal nach.

Update:
Dies hatten wir schon mehrfach. Dies passiert, wenn kein Bild ausgewählt wurde beim "Highlighted Inhaltsbanner", da dies als Default-Bild verwendet wird. Ich habe nun einen transparent Pixel hinterlegt. Dies könnte ich auch als Fallback einbauen, falls es kein Default-Bild gibt. Was meinst du dazu @larsUE?

Ganz spezifisch bist du anscheinend dem Prozess "Einen Post aufschalten" gefolgt, der anscheinend nicht wirklich angezeigt werden sollte?

**Comment by larsUE** [comment]
Das wird tatsächlich noch benötigt. Kann es also sein, dass für Winterthur einfach kein Default-Bild definiert wurde?

**Comment by larsUE** [comment]
@Kagemaru Das hast du gefixed, oder? Bei mir läufts auf alle Fälle wieder :)

**Comment by Kagemaru** [comment]
Ja, siehe den Update in meinem comment. Ich habe mal ein Transparentes Bild als Default hinterlegt. Evtl. sollten wir hier mal ein transparentes Bild fest im Code hinterlegen, falls es kein Highlighted Content Banner gibt.

**Comment by larsUE** [comment]
Ah sorry, hab das Update im Post übersehen! Transparentes Bild ist mal super. Danke dir!

**Comment by larsUE** [comment]
Meinst du, das könnte auch ein Bug sein, den wir verursachen? Auf der Zürcher Plattform werden z.B. Vorschläge ohne Bilder nicht mit einem Default-Bild angezeigt, sondern ganz ohne Bild. Siehe hier im Vergleich: https://mitwirken.integ.stadt-zuerich.ch/processes/feedback/f/34/proposals

Ich nehme an, Luzern hat das spezifisch entwickeln lassen? Ich würde da wohl nicht mehr zu viel im Code machen, da mit dem Redesign dann eh alles anders aussieht.

**Comment by larsUE** [comment]
Das Bild wird gezogen vom highlighted Banner, und wenn das keines vorhanden ist, dann gibts 500er

**Comment by Kagemaru** [comment]
Ist nun auf INT

**Comment by larsUE** [comment]
Irgendwie klappt das bei mir noch nicht: So erhalte ich hier weiterhin einen 500er: https://cokreation.test.winterthur.ch/profiles/lars_kaiser/following

**Comment by carlobeltrame** [comment]
Wurde laut Lars in #115 gleich zufällig mitgelöst.
