### ISSUE TITLE
Datumshack für Prozessschritte aus Zürich übernehmen

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#112]
https://github.com/puzzle/decidim-zuerich/commit/0eee7cb712960dbcd20ab0d0f125c7cead8e3898 übernehmen.

Im Moment müssen bei Prozesschritten zwei unterschiedliche Daten angegeben werden. Wenn nur ein Datum ausgefüllt wird, erscheint das Datum dennoch als Spanne (`23. September 2023 – ?`). Für eintägige Prozessschritte ist das sehr unschön. Deshalb haben wir für Zürich einen kleinen Hack entwickelt.

Der Hack funktioniert wie folgt: 
1. Wenn nur ein Datum angegeben wird, dann erscheint das Datum ohne Spanne
2. Wenn kein Datum angegeben wird, dann erscheint der Text «Kein Datum angegeben». @kagemaru: Ist das per Key konfigurierbar?

Denkbar wäre auch die Option, dass wenn
a) Start- und Enddatum gleich sind (die Checks müssten dafür abgeschaltet werden) nur ein einzelnes Datum erscheint
b) Nur ein Start bzw. Enddatum ist es wie bisher angezeigt wird, damit offene Phasen weiterhin möglich sind (z.B. Prozesse ohne fixes Enddatum -> Erfahrungsgemäss haben diese Prozesse aber gar keine Schritte, was heute bereits möglich ist).

**Comment by carlobeltrame** [comment]
Habe das übernommen und auf INT ausgerollt. Translation Key ist `decidim_ocl.participatory_processes.participatory_process_helper.step_dates.no_dates`

**Comment by larsUE** [comment]
Alles bestens, danke!
