### ISSUE TITLE
PW eines spez. Accounts zurücksetzen geht nicht

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#113]

**Comment by innosmith** [comment]
Diverse Tests zeigen, dass die Änderung von Passwörtern von User-Accounts funktioniert. Auf Impuls Köniz gibt es einen User kommunikation@koeniz.ch, zu welchem wir das Passwort nicht zurücksetzen können. Es passiert entweder nichts oder ein Server-Fehler tritt auf, siehe Screenshot (beachte die URL). Any ideas, weshalb dies nicht funktioniert resp. wie wir dies fixen könnten?



![Image](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/be58f54f-55a4-4641-a29e-89a2cfd20685)

**Comment by larsUE** [comment]
Ja, das passiert wenn der User die Terms and Conditions nicht angenommen hat. Es hat einen Key, der da fehlerhaft übersetzt wird. Das ist das gleiche Problem, wie wir vor wenigen Tagen auf MeinQuartier auch hatten. Es ist der Kex `decidim.pages.terms_and_conditions.refuse.modal_body`, wo du `%{data_portability_path}` mit `%{download_your_data_path}` ersetzen musst. Es kann sein, dass dieser Fehler sonst noch auftritt, ich würde den fehlerhaften Key mit dem Term Customizer suchen. Bei Crowdin ist der Fehler bereits eingepflegt, aber wohl erst nach dem letzten Release.

**Comment by innosmith** [comment]
Vielen Dank @larsUE , das war der Fehler!
