### ISSUE TITLE
Survey multiple answers einrichten

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#119]
Bitte Aufwand 50/50 auf Köniz/deinKlima einrichten.

https://github.com/OpenSourcePolitics/decidim-module-survey_multiple_answers

**Comment by nicolefreypuzzle** [comment]
Für deinKlima/WA und impuls-Köniz

**Comment by nicolefreypuzzle** [comment]
@innosmith 

Aufwandschätzung:
Installation: 2h + Deployment
Zusätzlicher Aufwand bei jedem zukünftigen Decidim-Upgrade: 2h.
Plus: Deinstallation wenn das mal in kompatibler Form in Decidim integriert wurde: 2h + Deployment

**Comment by innosmith** [comment]
Funktioniert, danke @Kagemaru . Ready for PROD.
