### ISSUE TITLE
500er auf Debatten

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#126]
Die folgende Komponente schmeisst bei mir immer einen 500er: https://gemeinsamer.space/assemblies/zw/f/670/

Möglicher Zusammenhang mit https://github.com/puzzle/decidim-zuerich/issues/434 prüfen

**Comment by nicolefreypuzzle** [comment]
Robin prüft, danach Besprechung Massnahmen (auch wegen Kosten-Übernahme)

**Comment by Robin481** [comment]
Hallo @larsUE ich kann den 500er Fehler nicht nachstellen.
Der Link den du oben verlinkt hast löst bei mir, ob eingeloggt oder nicht, keinen 500er aus.

Hat es sich inzwischen magisch gelöst oder tritt es bei dir immernoch auf? Falls es immernoch auftritt würde es eventuell Sinn machen in ein GoogleMeet zu sitzen das du es auslösen kannst und ich dabei in die Logs schaue.

**Comment by larsUE** [comment]
Komisch, bei tritt er nur angemeldet auf. Hast du jetzt kurz Zeit für ein Meets? Bin noch bis 13 Uhr erreichbar

**Comment by larsUE** [comment]
Lustigerweise tritt er in dem Modul, in dem ich den Fehler ursprünglich festgestellt habe, nicht mehr auf. In der neu erstellten Komponente tritt er bei mir noch auf, so z.B. hier: https://gemeinsamer.space/assemblies/zw/f/670/debates/73

**Comment by Robin481** [comment]
Sorry das Mail das du nur kurz Zeit hast ist natürlich erst jetzt gekommen 😁 
Auch in deinem neuen Link passiert es bei mir nicht. 
Ich schreibe dir gleich eine Mail für eine neue Terminfindung :)

**Comment by larsUE** [comment]
Konnte aber den Fehler den Logs entnehmen:

```
I, [2024-06-18T13:16:54.632796 #1]  INFO -- : [7955c026-e04f-41ef-b9c3-95a5b66b1108] method=GET path=/assemblies/zw/f/670/ format=html controller=Decidim::Debates::DebatesController action=index status=500 error='ActionView::Template::Error: missing interpolation argument :resource_name in "Sie folgen <span class=\"show-for-sr\">%{resource_name}</span>" ({:space_name=>"Zentralwäscherei"} given)' allocations=77189 duration=112.89 view=0.00 db=18.14 time=2024-06-18 11:16:54 UTC params={"assembly_slug"=>"zw", "component_id"=>"670"} host=gemeinsamer.space user_id=1763
I, [2024-06-18T13:16:54.668435 #1]  INFO -- : [7955c026-e04f-41ef-b9c3-95a5b66b1108] Sending event 9c7591672d564aa9a0d58a7b5c58f685 to Sentry
F, [2024-06-18T13:16:54.725363 #1] FATAL -- : [7955c026-e04f-41ef-b9c3-95a5b66b1108]   
[7955c026-e04f-41ef-b9c3-95a5b66b1108] ActionView::Template::Error (missing interpolation argument :resource_name in "Sie folgen <span class=\"show-for-sr\">%{resource_name}</span>" ({:space_name=>"Zentralwäscherei"} given)):
[7955c026-e04f-41ef-b9c3-95a5b66b1108]     1: <%= card_for debate, from: debate %>
[7955c026-e04f-41ef-b9c3-95a5b66b1108]   
[7955c026-e04f-41ef-b9c3-95a5b66b1108] app/cells/decidim/follow_button/show.erb:21:in `block in __tilt_192940'
[7955c026-e04f-41ef-b9c3-95a5b66b1108] app/cells/decidim/follow_button/show.erb:14:in `__tilt_192940'
Basically erwartet es das die Variable :resource_name definiert ist bei uns ist aber nur :space_name definiert.
```

Vermutlich kannst du das ganze also einfach am richtigen Ort umbenennen und dann klappt es wieder.

**Comment by larsUE** [comment]
Gelöst, indem ich den Key `decidim.follows.create.participatory_space ` überschrieben habe. 
Alter Wert: `Sie folgen <span class="show-for-sr">%{resource_name}</span>`
Neuer Wert: `Sie folgen %{space_name}`
