### ISSUE TITLE
Anonymous access codes einbauen

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#127]
Analog Plattform Zürich umsetzen für Tenant Luzern: https://github.com/puzzle/decidim-zuerich/issues/423

Zieltermin: Möchte seitens Luzern in KW28 produktiv verwendet werden

**Comment by nicolefreypuzzle** [comment]
analog Plattform Zürich: https://github.com/puzzle/decidim-zuerich/issues/423

**Comment by nicolefreypuzzle** [comment]
Zieltermin: Möchte seitens Luzern in KW28 produktiv verwendet werden

**Comment by Robin481** [comment]
Habe eine Lücke gefunden und konnte das gleich umsetzen.
@NicolaNaf es ist auf der Testumgebung deployed und du kannst es testen :)

**Comment by larsUE** [comment]
@NicolaNaf ich würde dieses Ticket ordnungshalber mal close, einverstanden?

**Comment by larsUE** [comment]
@NicolaNaf ich würde dieses Ticket ordnungshalber mal closen, einverstanden?

**Comment by NicolaNaf** [comment]
Ja gerne, danke dir!

Von: Lars Kaiser ***@***.***>
Gesendet: Donnerstag, 18. Juli 2024 16:27
An: decidim-swiss/decidim.swiss ***@***.***>
Cc: Näf Nicola ***@***.***>; Mention ***@***.***>
Betreff: Re: [decidim-swiss/decidim.swiss] Anonymous access codes einbauen (Issue #127)

 Denken vor Klicken: Verdächtige E-Mails bitte mit Hilfe der Schaltfläche melden.




@NicolaNaf<https://github.com/NicolaNaf> ich würde dieses Ticket ordnungshalber mal closen, einverstanden?
