### ISSUE TITLE
Umfrage kann nicht gelöscht werden

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#131]
Fehlermeldung: Beim Löschen dieser Komponente ist ein Fehler aufgetreten.
Egal, ob die Umfrage veröffentlicht ist oder nicht

Passiert auf impuls köniz (Auf G wie grün. der Bläuacker), funktioniert aber auf Wyss Academy-Umgebung deinklima.

Umfrage (korrigiert) nicht verändern, restliche dürfen gelöscht werden.

**Comment by nicolefreypuzzle** [comment]
Fehlermeldung: Beim Löschen dieser Komponente ist ein Fehler aufgetreten.
Egal, ob die Umfrage veröffentlicht ist oder nicht

Passiert auf impuls köniz, funktioniert aber auf Wyss Academy-Umgebung.

**Comment by larsUE** [comment]
Eine Umfragekomponente kann nur gelöscht werden, wenn keine Antworten vorhanden sind. Vielleicht liegts daran? Also zuerst Umfrageantworten löschen, dann die Komponente.

**Comment by nicolefreypuzzle** [comment]
Wir haben drüber gesprochen, Decidim hat eine Validierung, die das Löschen vom Umfragen ohne das Entfernen der Antworten nicht ermöglicht.

**Comment by larsUE** [comment]
@innosmith zu deiner Frage im anderen Ticket: Nein, das widerspricht der Grundhaltung von Decidim, nichts löschen zu können, solange noch Nutzerinhalte vorhanden sind -> denn über die soll ja ein Plattformadmin eigentlich nicht verfügen dürfen. Bei der Umfrage ist das etwas unsinnig, aber immerhin wird so erschwert, dass Daten aus Versehen gelöscht werden.

**Comment by innosmith** [comment]
Es klappt jetzt mit dem Löschen, nachdem die Umfrage selbst z.B. um eine weitere Frage ergänzt wurde. Der Prozess dafür ist aber alles andere als benutzerfreundlich.
