### ISSUE TITLE
Umfrage mit Bilder: Werden Texte nach Bild-einfügen geändert, werden alle Bilder rausgelöscht

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#132]

**Comment by Kagemaru** [comment]
Das scheint dieses Issue wiederzuspiegeln: https://github.com/slab/quill/issues/3806

Um dies zu umgehen, muss der Quill Editor aktualisiert werden. Dieser ist Teil von Decidim direkt, wenn ich mich recht erinnere.

**Comment by innosmith** [comment]
@Kagemaru : was würde das konkret bedeuten zu aktualisieren? Welchen Aufwand schätzt du dafür?

**Comment by larsUE** [comment]
Der Quill-Editor ist in der Tat sehr buggy und wird deshalb auch in V0.28 durch einen anderen Editor (TipTap) ersetzt.

**Comment by innosmith** [comment]
Dann wäre die Empfehlung auf das Upgrade V0.28 resp. V0.29 zu warten?

**Comment by larsUE** [comment]
Kommt auf die Dringlichkeit und Budget an ;) Ich vermute, Decidim wird das Quill-Update nicht übernehmen, weil sie ja in den aktuellsten Versionen einen anderen Editor einsetzen. Diesen habe ich eben (weil das gerade in Zürich auch Thema war) auf [Nightly](https://nightly.decidim.org) getestet und muss sagen, das wird deutlich besser und intuitiver!

Als Hack funktioniert manchmal, vor dem Bild ein Zeilenabstand einzufügen. So kann ich in Zürich jeweils sicherstellen, dass die Bilder nicht verschwinnden.

**Comment by larsUE** [comment]
Zusammengefasst: Ich glaub, der Aufwand sollten wir uns sparen und allfälliges Budget nutzen, um dann im neuen Jahr möglichst schnell auf 0.29/0.30 zu wechseln.

**Comment by innosmith** [comment]
Danke für deine Einschätzung @larsUE . Ich schliesse mich dem an.
