### ISSUE TITLE
Umfrage: Konfig "Antworten bei Veröffentlichen der Komponente löschen" funktioniert nicht (Antworten werden nicht gelöscht)

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#133]

**Comment by larsUE** [comment]
Hat auf dem gemeinsamer.space immer funktioniert. Hier die Anleitung aus Zürich: 

> Antworten löschen / Umfrage nach ersten Antworten bearbeiten
> Wenn bereits Antworten auf die Umfrage abgegeben wurden, können Sie die Fragen nicht mehr beantworten. Um dies wieder zu ermöglichen, müssen Sie zunächst die Antworten löschen. Gehen Sie wie folgt vor:
> 
> Stellen Sie sicher, dass in den Komponenteneinstellungen ein Häkchen bei «Antworten bei Veröffentlichung der Komponente löschen.» gesetzt ist (sehen Sie sich dazu das Kapitel «Komponente einrichten» an). Speichern Sie die Einstellungen.
> 
> Setzen Sie als nächstes die Umfrage auf «Unveröffentlicht»
> 
> Nun müssen Sie die Umfrage anpassen. Sobald Sie die Anpassung speichern, werden alle Antworten gelöscht. 
> 
> Die Umfrageantworten wurden nun gelöscht. Du kannst das Formular nun erneut veröffentlichen.
> Wichtig: Diese Funktion kann im Livebetrieb zu einem unbeabsichtigtem Datenverlust führen. Wir empfehlen also, das Häkchen nur im Testbetrieb zu setzen, bzw. nach dem bewussten Löschen wieder zu entfernen.

Es gibt hierzu allerding tatsächlich noch einen Bug, welcher hier bei Decidim gemeldet wurde: https://github.com/decidim/decidim/issues/12386

**Comment by Robin481** [comment]
@innosmith  Lars hat da schon das meiste richtig beantwortet.
Ich habe das auch noch bestätigt indem ich via Konsole die angehängen Antworten gelöscht habe. Das Löschen der Komponente hat dann ohne Problem geklappt.

**Comment by innosmith** [comment]
@Robin481 Es sollte doch möglich sein, die Umfragekomponente zu löschen, ohne zuerst alle Antworten löschen zu können. Oder sehe ich das falsch?

**Comment by nicolefreypuzzle** [comment]
@innosmith @Robin481 ihr kommuniziert über den falschen Task, diese gehören zu Task https://github.com/decidim-swiss/decidim.swiss/issues/131.

@innosmith wir haben drüber gesprochen, Decidim hat eine Validierung, die das Löschen vom Umfragen ohne das Entfernen der Antworten nicht ermöglicht.

**Comment by innosmith** [comment]
Das Feature funktioniert nur, wenn zuerst die Umfrage selbst verändert wurde. Die Usability und Standard-Fehlermeldungen helfen nicht wirklich ;-)
