### ISSUE TITLE
Startseite: Kartenausschnitt - Ort falsch und Veranstaltungen werden nicht angezeigt

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#134]
Letzte Veranstaltungen werden in der Liste neben der Karte angezeigt, jedoch nicht auf der Karte (der Kartenausschnitt zeigt auch einen ganz anderen Ort an als die Umgebung der Veranstaltungen)

Auf INT und PROD.

**Comment by larsUE** [comment]
@innosmith: Ein kurzer Blick auf die Veranstaltung lässt mich vermuten, dass da im Adressfeld wohl keine Adressen hinterlegt wurden? Ich sehe aber nicht ins Backend rein.

**Comment by Kagemaru** [comment]
Im System Admin Backend kann dies pro Organisation eingestellt werden. Auf der PROD Umgebung waren die Felder leer und auf der INT Umgebung waren nur einzelne Werte eingetragen.
