### ISSUE TITLE
Migration OpenShift

### ISSUE THREAD

**Issue by nicolefreypuzzle** [decidim-swiss/decidim.swiss#136]

**Comment by nicolefreypuzzle** [comment]
In diesem Rahmen auch Task https://github.com/decidim-swiss/decidim.swiss/issues/128 erledigen

**Comment by larsUE** [comment]
Ich renne seit der Migration auf der Winterthurer INT  immer wieder in 403er. Sei es z.B. beim Upload von Bildern (geht meistens) oder beim Speichern der Decidim Awesome CSS Funktionen (geht gar nicht).

Könnt ihr euch das anschauen?

**Comment by Kagemaru** [comment]
Hey @larsUE

Das war ein Fehler beim Laden der Konfiguration in der WAF. Dies sollte jetzt behoben sein. Ansonsten assigned das Ticket nochmals mir, mit einer Notiz.

**Comment by larsUE** [comment]
Das passt nun, danke dir!
