### ISSUE TITLE
Konferenzveranstaltungen zusammen mit Assembly-Veranstaltungen anzeigen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#140]
Seht ihr einen einfachen Weg, um die Veranstaltungen einer Konferenz, welche derselben Organisation "Klimaneutrale Region Oberland-Ost" zugeordnet sind, zusammen mit den anderen "normalen" Veranstaltungen derselben Organisation im Frontend aufzulisten?

Annahme bezüglich Umsetzung: Beim Anzeigen der "normalen" Veranstaltungen muss eine zusätzliche DB-Abfrage gemacht werden, welche prüft, ob eine Organisation Konferenzen zugeordnet ist mit Veranstaltungen und falls ja, diese ebenfalls mit in die Collection zur Anzeige zu geben.

Unschöner Workaround: Wir führen die Veranstaltungen doppelt.

![Image](https://github.com/user-attachments/assets/4e60ccfa-812e-4fe1-87a0-98fc729e20b6)
![Image](https://github.com/user-attachments/assets/574531b7-03b6-4c0c-a5e7-bac4bf122a60)

**Comment by nicolefreypuzzle** [comment]
Lösung nicht ganz klar, DEV müsste analyisieren. Aufwand unklar.
Anthony prüft noch mal mit Kunde, danach Feedback an uns.

**Comment by larsUE** [comment]
@innosmith Wenn du über die allgemeine Veranstaltungsseite /meetings gehst, dann kannst du nach Herkunft (Prozesse/Assemblies/Konferenzen) filtern und diesen Link speichern. So hast du zumindest mal alle Veranstaltungen am selben - aber wohl noch nicht am gewünschten Ort. 

Beispiel für deinen Use Case: https://deinklima.ch/meetings/meetings?filter%5Btitle_or_description_cont%5D=&filter%5Bwith_any_date%5D=&filter%5Bwith_any_date%5D=upcoming&filter%5Bwith_any_type%5D%5B%5D=&filter%5Bwith_any_scope%5D%5B%5D=&filter%5Bwith_any_global_category%5D%5B%5D=&filter%5Bwith_any_origin%5D%5B%5D=&filter%5Bwith_any_space%5D%5B%5D=&filter%5Bwith_any_space%5D%5B%5D=decidim%2Fparticipatory_process&filter%5Bwith_any_space%5D%5B%5D=decidim%2Fconference

P.S. Gratuliere zur ersten Anwendung der Konferenzen in der Deutschschweiz!

**Comment by innosmith** [comment]
Danke für die Idee @larsUE. Ich werde dies vermutlich nicht anwenden können, da die gemeinsamen Veranstaltungen beim Klick auf den Tab Veranstaltungen der Organisation angezeigt werden sollten. So müsste ich einen Hack im Frontend machen können.

PS: Bei BOLD Ideas 2021 habe ich bereits intensiv das Konferenzmodul verwendet in Kombination mit den Participatory Processes ;-)

**Comment by innosmith** [comment]
Der Kunde wünscht eine Aufwandschätzung für die weitere Diskussion. Kostendach dafür 1h?

**Comment by nicolefreypuzzle** [comment]
@NicolaNaf zur Info, Link zum Ticket

**Comment by nicolefreypuzzle** [comment]
@Kagemaru wie besprochen bitte Aufwand schätzen und an mich senden.

**Comment by innosmith** [comment]
Der Kunde hat eben entschieden, doch darauf zu verzichten. Deshalb @Kagemaru, @nicolefreypuzzle  bitte keine Aufwandschätzung mehr machen und das Ticket als abgeschlossen betrachten.
