### ISSUE TITLE
Ein Projekt wird nicht angezeigt

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#16]
Ich versuche das Projekt https://deinklima.ch/processes/stadtxypartizipation unter "Projekte" in der Navigation angezeigt zu bekommen. Rufe ich die URL direkt auf, wird das Projekt angezeigt. Wenn ich das Projekt hervorhebe, wird es angezeigt, sonst nicht?!? Any ideas what I'm doing wrong?

**Comment by carlobeltrame** [comment]
Die Komponente gibts leider nicht mehr. Sentry-Fehler ist aber hier: https://sentry.puzzle.ch/pitc/decidim-luzern/issues/57432/
Ich kann mir den Fehler nur erklären, wenn die Page in der Komponente irgendwie gelöscht wurde... Kannst du das nochmals reproduzieren oder hat dir da vielleicht jemand reingefunkt? Ansonsten sehe ich nichts was ich beheben könnte.

EDIT: Ähm, du hast die Beschreibung des Issues komplett geändert... Meine Antwort hat sich noch auf den ursprünglichen Text bezogen, den ich noch per Mail bekommen habe.

**Comment by larsUE** [comment]
@innosmith Meinst du die Darstellung auf der Startseite oder unter "Projekte"?

Erfahrungsgemäss ist das häufig ein Problem mit den Prozessdaten: Sind vergangene gesetzt, wird das Projekt nur unter vergangene angezeigt, sind gar keine Daten gesetzt wird das Projekt tatsächlich nicht angezeigt. Und wenn das Projekt erst in Zukunft beginnt, wird es beispielsweise auf der Startseite nicht angezeigt, sondern erst dann, wenn es läuft.

**Comment by innosmith** [comment]
Problem solved: Das Projekt (Prozess) war einer leeren anstatt keiner Projektgruppe zugeordnet. Weil die Projektgruppe komplett leer war, also auch kein Name, habe ich gemeint das wäre der Standard für "keiner Projektgruppe zugeordnet". Danke @carlobeltrame und @larsUE. Die leere Projektgruppe entstand vermutlich beim Import des Projektes, welches auf eine Projektgruppe referenzierte, welch es im Zielsystem nicht gibt.

**Comment by larsUE** [comment]
Dieser Bug (ergo dass leere Prozessgruppen generiert werden) wird mit V0.28 gefixed und backported auf V0.27.3 und V0.26.7 (beide gestern erschienen): https://github.com/decidim/decidim/pull/10733
