### ISSUE TITLE
URL's einrichten

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#17]
Bitte folgende gekauften Domains direkt auf entsprechende Zieladressen auf deinklima.ch weiterleiten.

plusenergiestadt.ch auf https://deinklima.ch/assemblies/plusenergiestadt
-> dies ist eine geschlossene Organisation und dient den berechtigten Personen dem einfacheren finden der Org.

co2neutraleregion.ch auf https://deinklima.ch/co2neutraleregion

**Comment by bsantschi** [comment]
Hoi @innosmith 

- die Weiterleitung für plusenergiestadt.ch habe ich eingerichtet.
- co2neutraleregion.ch habe ich noch keine Lösung, denn dort haben wir bereits auf Metanet ein Webhosting mit E-Mailweiterleitung. Ich gehe davon aus, dass bei der Umstellung auf eine Website-Weiterleitung in Metanet die E-Mail-Weiterleitung nicht mehr möglich ist. Vielleicht kennst du dich da aber besser aus. Oder du entscheidest, ob ihnen die Website-Weiterleitung oder E-Mailweiterleitung wichtiger ist.

**Comment by innosmith** [comment]
Hoi @bsantschi : für co2neutraleregion.ch kannst du direkt in der DNS-Config unterschiedliche Ziele für Mail und Website angeben. Thomas Burkhalter kann dir wahrscheinlich direkt weiterhelfen.

**Comment by bsantschi** [comment]
DNS ermöglicht leider keine Weiterleitung auf eine Unterseite (https://deinklima.ch/co2neutraleregion), nur auf eine andere Domain. Daher muss ich das via Plesk konfigurieren und dort habe ich noch nicht herausgefunden, wie das geht ohne die E-Mailweiterleitung zu beeinflussen. Ich schaue noch mit Thomas.

**Comment by innosmith** [comment]
Stimmt; und ja vielleicht hat Thomas noch eine Idee.

**Comment by bsantschi** [comment]
Hoi Anthony, wir sind betr. Weiterleitung co2neutraleregion.ch noch nicht weiter. Könntest du abklären, ob die Auftraggeberin allenfalls auf die E-Mail- oder auf die URL-Weiterleitung verzichten könnte? Wenn wir nur eine der beiden Weiterleitungen einrichten müssten, wäre das mit wenig Aufwand möglich. Sollte beides zwingend weitergeleitet werden, werden wir uns dem vertiefter annehmen (aber auch mehr Budget belasten).

**Comment by innosmith** [comment]
Hoi @bsantschi : @Kagemaru meinte gestern beim Standup, dass ihr verschiedene Varianten hättet, dies umzusetzen. Ich habe den Kollegen mitgeteilt, bitte die einfachste Variante umzusetzen. Dem Kunden habe ich dies auch schon mitgeteilt. Das Fallback-Szenario wäre, die Domain co2neutraleregion.ch auf die Hauptdomain deinklima.ch weiterzuleiten.

**Comment by bsantschi** [comment]
Thomas konnte es umsetzen, vielen Dank!

**Comment by bsantschi** [comment]
Somit sind plusenergiestadt.ch und co2neutraleregion.ch eingerichtet.

**Comment by Kagemaru** [comment]
co2neutraleregion.ch habe ich per Redirect auf der index.html eingerichtet.
