### ISSUE TITLE
Bilderkarussell funktioniert nicht bei allen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#20]
Gewisse städtische Anwender sehen auf der Startseite nur einen weissen Platzhalter. Die Stadt Thun setzt Microsoft Edge, Version 105.0.1343.42 (Offizielles Build) (64-Bit) ein. Javascript sei aktiviert. Was ist die Browser-Mindestanforderung für das Bilderkarussell?

Ist es möglich, dass wir auf der Startseite abhängig der Browser-Version oder Javascript-Einstellungen das Bilderkarussell (Option 1) oder nur ein statisches Bild (Option 2) anzeigen? Falls ja, bitte entsprechend umsetzen und für das statische Bild das letzte Bild aus dem Karussell verwenden, bei welchem das Logo ganz sichtbar ist.

**Comment by carlobeltrame** [comment]
Bei mir in Edge 105.0.1343.50 (Official build) (64-bit) funktioniert es ohne Probleme. Es könnte vielleicht daran liegen dass wir die Bilder von einer externen Domain laden (co2neutraleregion.ch) und gewisse Privacy-Browser-Plugins oder grosszügige Adblocker das mal generell blockieren.

Ich könnte einfach ein statisches Bild "hinter" das Karussell legen. Aber wenn dieses Bild auch wieder von der gleichen externen Quelle kommt bringt das auch wieder nichts. Ich könnte die Bilder auch direkt in Decidim hosten, aber dann verliert ihr die explizit gewünschte Flexibilität, die Bilder selber austauschen zu können.

**Comment by innosmith** [comment]
@carlobeltrame : wie wäre es, das letzte Bild mit dem vollständigen Logo abgebildet zusätzlich als Hintergrundbild auf Decidim zu hosten? So verlieren wir nur die Flexibilität, das letzte Bild nicht selber anpassen zu können. Sobald umgesetzt, kann ich die Stadt Thun bitten, dies zu testen.

**Comment by carlobeltrame** [comment]
Habe das umgesetzt und auf die Integration test.deinklima.ch aufgeschaltet. Bitte testen mit den betroffenen Browsersn

**Comment by innosmith** [comment]
@carlobeltrame : Wenn ich Javascript deaktiviere, wird nicht das letzte Bild statisch angezeigt. Bitte noch anpassen. Leider können wir nicht kurzfristig das Browser-Setup in Thun testen. Wir hoffen, dass es mit den Änderungen funktioniert.

**Comment by carlobeltrame** [comment]
Ich habe es jetzt noch leicht angepasst und mit Safari Versionen 11, 13 und 15 getestet, es sieht jetzt überall gleich aus. Sobald das Bild auf der Produktion deployed ist führe ich das dort noch nach.

**Comment by innosmith** [comment]
Danke für das Testing und PROD-Deployment @carlobeltrame . Das Szenario, wenn ich Javascript deaktiviere, zeigt immer noch ein anderes Bild anstelle des Schlussbildes an, siehe Screenshot. Kannst du das einfach noch ändern oder benötigt das erneut ein PROD-Deployment?

<img width="1700" alt="Bildschirmfoto 2022-10-19 um 14 14 26" src="https://user-images.githubusercontent.com/75796635/196688342-cad52997-5da5-4127-8c94-a1dd0a080a21.png">

**Comment by carlobeltrame** [comment]
Hoi Anthony, wie am Dienstag besprochen ist das Problem bei Thun mit grosser Wahrscheinlichkeit nicht, dass JavaScript deaktiviert ist, und wenn du JavaScript deaktivierst reproduzierst du nicht dieselben Probleme die sie gemeldet haben. Wäre JavaScript deaktiviert würde noch viel mehr in Decidim nicht funktionieren, darunter das Nutzungsbedingungen-Banner, das "Anthony Smith"-Dropdown-Menü, die Logout-Funktion, jegliche Karten, Prozessfilter, und noch vieles mehr. JavaScript zu deaktivieren ist kein von Decidim unterstützter Use Case. Daher habe ich das nicht gefixt. Um das nichtsdestotrotz zu fixen müsste ich das Karussell nochmals gröber umbauen. Ein Produktivdeployment wäre dafür nicht nötig, aber ich müsste nochmals über die Bücher, wie ich das Karussell am einfachsten umsetzen würde mit dieser neuen Anforderung. Bitte bestätige das nochmals explizit, falls ihr das wünscht.

Stattdessen habe ich, wie mündlich besprochen, die Probleme in Safari gefixt, welche Lars gerade noch aufgefallen waren. Das ist es was ich auf Integration und inzwischen auf auf Produktion aufgeschaltet habe.
