### ISSUE TITLE
Aufforderung Verifikation nach Emailbestätigung

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#22]
Wenn sich auf deinKlima PROD ein User registriert, erhält er/sie im Anschluss eine Email zur Bestätigung der Emailadresse. Wird der Link geklickt, gelangt der/die User:in direkt ins User-Profil zu den Verifikationseinstellungen. Auf dieser Seite wird der neue User "aufgefordert", seine Telefonnummer zur Verifikation einzugeben. Ist dies ein neues (ungewolltes) Feature von v0.26 oder ein Fehler?

Nachfolgend die Email für neu Registrierte sowie die URL zur Bestätigung; und die die Zieladresse zur Verifikation:
<img width="1145" alt="Bildschirmfoto 2022-09-14 um 09 17 05" src="https://user-images.githubusercontent.com/75796635/190087189-f0b9fa67-2c1d-4dec-b8c9-f892c548e581.png">

http://deinklima.ch/users/confirmation?confirmation_token=o_B8FAVLv4DXxTjW71K9

Roten Textkommentar im Bild ignorieren, hat nichts mit diesem Ticket zu tun.
<img width="1529" alt="Bildschirmfoto 2022-09-14 um 08 43 31" src="https://user-images.githubusercontent.com/75796635/190086534-5b153fa6-5815-4b75-8fd4-65fb71625e65.png">

**Comment by larsUE** [comment]
Das Standardvorgehen für neue Nutzende bei der Registrierung war m.E., dass man nach der Registrierung direkt auf die Profilseite weitergeleitet wurde. Diese neue Weiterleitung funktioniert nur, wenn Verifikationen aktiviert sind. Deshalb konnte ich das Verhalten auch auf der Zürcher Seite nachstellen. Ich finde das aber auch unsinnig und würde auf das oben beschriebene vorherige Verhalten zurück gehen.

**Comment by carlobeltrame** [comment]
Dieses Verhalten war schon seit spätestens 2018 so. Es müssen aber folgende Bedingungen gelten, damit der User nach der Registrierung zu den Verifikationen gelangt:
- User darf kein Admin sein
- Kein Redirect für nach der Registrierung ist gespeichert, also der User hat sich nicht via eine Aufforderung z.B. beim Kommentarfeld registriert, sondern ganz normal via "registrieren" Link
- User loggt sich zum ersten Mal ein
- Verifikationen sind aktiviert
- User hat entweder eine bestätigte Mailadresse, oder wird impersoniert oder "gemanaged" (habe nicht gegraben was das heisst)
- User ist nicht blockiert

Wegen diesen vielen Bedingungen gehe ich davon aus dass das bisher einfach noch nicht aufgefallen ist.

@larsUE verstehe ich dich richtig dass du das auch gleich auf der Zürcher Plattform geändert haben willst?
