### ISSUE TITLE
Karussell deaktivieren wegen Performance

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#29]
Von verschiedenen Seiten kam das Feedback, dass die Ladezeit der Startseite noch zu langsam ist. Wir haben nun entschieden, folgende Anpassungen umzusetzen:

1. Das Karussell verschwindet und nur noch das letzte Bild statisch angezeigt
2. Das letzte Bild (mit dem zusammengesetzten Logo) wird in der Auflösung weiter reduziert, sodass es noch nicht verpixelt wirkt. Vermutlich hilft es auch, das statische Bild direkt auf dem Decidim-Server zu haben.

Merci

**Comment by carlobeltrame** [comment]
Ist auf Integration umgesetzt. Bitte testen.

**Comment by innosmith** [comment]
Bitte auf PROD deployen @carlobeltrame . Sobald wir das Design von deinklima.ch überarbeiten, setzen wir es dann ev. analog Dialog Luzern und MeinQuartier um, wo das Logo als sep. Layer mittig über das Startbild gelegt wird. Inkl. der Möglichkeit, das Startbild selbst als Plattform-Admin anzupassen.
