### ISSUE TITLE
Anpassung Kacheldesign Projekte

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#30]
Bitte das Kacheldesign der Projekte in der Übersicht gemäss nachfolgendem Mockup mittels CSS anpassen.

Bitte anpassen:
1. Unterhalb des Bildes, rechts angeordnet auf gleicher Höhe wie der Titel das Projekt-Icon der Startseite
2. Die Zeile mit Start- und Endedatum entfernen
3. Neu eine Zeile mit dem Organisationsbezug (Organisationsname) des Projektes, sofern vorhanden. Falls mit URL linkbar, bitte verlinken. Vorgängig zum Organisationsnamen links angeordnet das Organisationslogo der Startseite.
4. Die letzte Zeile mit dem aktuellen Schritt und der Möglichkeit der Beteiligung als Button bitte entfernen. In einem späteren Schritt, sobald Projekte mit digitaler Beteiligungsmöglichkeit auf der Plattform vorhanden sind, werden wir diesen Button ev. wieder anzeigen wollen.

<img width="597" alt="Bildschirm­foto 2022-11-04 um 15 13 11" src="https://user-images.githubusercontent.com/75796635/199999546-e6f34618-d9ff-480f-ab9f-1cbe8749750c.png">

**Comment by carlobeltrame** [comment]
Die neue Zeile lässt sich nicht mit nur CSS einfügen. Daher wird ein Produktivdeployment nötig sein, und ich muss es abhängig vom Tenant machen.

**Comment by innosmith** [comment]
@carlobeltrame : wäre eine Code-Anpassung auch notwendig, wenn wir die Organisation anders darstellen, so wie z.B. bei den Veranstaltungen in Luzern? Falls eine Code-Anpassung notwendig, wie aufwändig würde das?

**Comment by carlobeltrame** [comment]
Ja, das ist technisch intern genau das gleiche, eigentlich egal wo auf der kachel die Organisation stehen soll. Inklusive ausblenden der anderen Elemente und Deployments auf Integration und Produktion schätze ich 4-5 Stunden

**Comment by larsUE** [comment]
Darf ich vorschlagen, das nicht tenant-spezifisch zu lösen, sondern allgemein und dann bauen wir es auf den anderen Plattformen je nach Bedarf mittels CSS aus? Die einzelnen Zeilen der Cards lassen sich nämlich problemlos ansteuern. In Zürich zeigen wir je nach Prozess gar andere Zeilen an. Und dieses Feature könnte für weitere Tenants spannend sein (z.B. Winterthur).

**Comment by innosmith** [comment]
@carlobeltrame : Danke für die Aufwandschätzung. 4-5 Stunden ist ok. Bei deinklima.ch stehen die Projekte im Zentrum, entsprechend ist diese View inkl. CSS Flexibilität für weitere Anpassungen wichtig. Wenn die Idee von @larsUE ohne grossen Mehraufwand möglich ist, gerne. Hat diese Umsetzung Einfluss auf die anderen Tenants auf decidim.swiss?

**Comment by carlobeltrame** [comment]
Der Vorschlag von Lars ist gleich einfach oder einfacher umzusetzen. Aber bei neuen Tenants wird dann halt standardmässig alles angezeigt, bis man es bewusst mit CSS versteckt.

**Comment by innosmith** [comment]
Dann lass es uns so umsetzen, dass bei neuen Tenants ungewünschte Zeilen mittels CSS ausgeblendet werden können; ist ja einfach anzupassen.

**Comment by carlobeltrame** [comment]
Wie per Mail besprochen, alle Teile ausser der Organisationsname sind jetzt mit reinem CSS umgesetzt und auf der Integrationsumgebung testbar.

**Comment by innosmith** [comment]
Bitte noch die Zeile mit "erstellt am und nicht mehr folgen" ebenfalls ausblenden gemäss neuem Mockup. Danke @carlobeltrame .

<img width="1711" alt="Bildschirm­foto 2022-11-10 um 10 24 41" src="https://user-images.githubusercontent.com/75796635/201052143-bd491c04-6f3c-4ead-b351-57547f454d1d.png">

**Comment by carlobeltrame** [comment]
Ist erledigt

**Comment by innosmith** [comment]
@carlobeltrame : Wir warten noch kurz mit der Umsetzung zur Anzeige des Organisationsnamens in den Projektkacheln. Wir müssen noch diskutieren, ob der Organisationsname unterhalb angezeigt werden soll oder analog bei den Veranstaltungen oberhalb des Bildes. Auf jeden Fall sollte der Organisationsname in beiden Fällen an derselben Stelle und gleich angezeigt werden.
