### ISSUE TITLE
Metadatenfeld verbreitern

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#31]
Bitte das Metadatenfeld auf der Startseite rechts bei Organisationen und Projekten um ca. 20% breiter machen, sodass der Kontaktname charlotte.kaufmann@wyssacademy.org bei der Wyss Academy Organisation nicht mehr abgeschnitten wird. Siehe Screenshot.

<img width="2004" alt="Bildschirm­foto 2022-11-04 um 15 34 37" src="https://user-images.githubusercontent.com/75796635/200002110-de2d661a-23ea-493f-ae07-1958d74cebdb.png">

**Comment by carlobeltrame** [comment]
Ich habe das auf der Integration umgesetzt, aber nur in der Organisation Wyss Academy for Nature (via Einschränkung auf der CSS Box). Grund ist, dass die Metadaten-Box jetzt je nach Bildschirmgrösse mehr als die Hälfte der Bildschirmbreite einnimmt. Falls wir das dennoch für alle Organisationen haben wollen können wir einfach die Einschränkung entfernen.

**Comment by innosmith** [comment]
Bestens, danke.
