### ISSUE TITLE
Header Projektübersicht anpassen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#32]
Bitte wenn einfach mit CSS möglich den Header der Projektübersichtsseite gemäss Mockup anpassen mit:

1. Text "Hervorgehobene Projekte" entfernen
2. Das Call to Action Bild mit Button auf die ganze Breite des hervorgehobenen Projektes verbreitern
3. Den Button "Projektidee eingeben" um ca. 25% vergrössern, sodass dieser besser zur Geltung kommt

Falls einfach mit CSS möglich, lassen wir diese Änderung solange stehen, bis einmal weitere Projekte einer neuen Kategorie hinzukommen.

<img width="2004" alt="Bildschirm­foto 2022-11-04 um 15 40 39" src="https://user-images.githubusercontent.com/75796635/200003082-8f4f384d-e62b-4a4e-a574-dfc171226622.png">

**Comment by carlobeltrame** [comment]
Ist auf Integration aufgeschaltet. Ich habe versucht dass das ganze auch auf Handys einigermassen gut aussieht.

**Comment by innosmith** [comment]
Bestens, danke.
