### ISSUE TITLE
SMS Kontingent pro Tenant konfigurierbar machen, deinklima Userkey und API-Passwort hinterlegen

### ISSUE THREAD

**Issue by bsantschi** [decidim-swiss/decidim.swiss#33]

**Comment by innosmith** [comment]
Ich warte noch auf den Kauf der SMS-Pakete durch Kundin.

**Comment by bsantschi** [comment]
- Hat Carlo auf PROD ausgerollt
- Carlo muss noch die Credentaisl (INT+PROD) eintragen und SMS Verifizierung aktivieren

**Comment by carlobeltrame** [comment]
SMS für deinklima ist jetzt auf INT und PROD eingerichtet. @innosmith bitte testen.

**Comment by innosmith** [comment]
> SMS für deinklima ist jetzt auf INT und PROD eingerichtet. @innosmith bitte testen.

Auf INT habe ich eine SMS erhalten für einen Testprozess. Annahme: auf PROD funktioniert es ebenfalls.
