### ISSUE TITLE
Designanpassungen Veranstaltungsübersicht

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#34]
Bitte auf der Veranstaltungsübersicht Designanpassungen mit CSS gemäss Mockup umsetzen. 

Bis etwas mehr Veranstaltungen auf deinklima sind, soll nur in der Veranstaltungsübersicht (nicht bei den Details zu den Veranstaltungen oder auf anderen Karten, z.B. Veranstaltungen einer Organisation) die Karte mit allen Veranstaltungen unsichtbar gemacht werden. Argument die Karte bringt aktuell zu wenig Infos, als dass diese soviel Platz einnehmen soll. Rest gemäss Mockup.

<img width="1518" alt="Bildschirm­foto 2022-11-12 um 21 46 57" src="https://user-images.githubusercontent.com/75796635/201494095-47db1065-b9c4-457d-8778-00f43c11e694.png">

**Comment by carlobeltrame** [comment]
@innosmith ist auf der Integration testbar

**Comment by innosmith** [comment]
Besten Dank @carlobeltrame . Bitte auf PROD übertragen.
