### ISSUE TITLE
Emailtexte werden nicht übernommen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#35]
Ist es möglich, dass bei der Registration neuer User noch ein Emailtext versendet wird, welcher nicht die Textübersetzung von Term Customizer nimmt? Details siehe Beschreibung und Screenshots (insb. der Letzte) von David seitens AUE nachfolgend. Falls wir dies vor dem 16.11.2022 lösen könnten, wäre super. Merci! 

By the way, wie können wir die Email-Templates hübscher machen? Haben wir hierfür eine Vorlage z.B. aus Zürich, welche wir adaptieren könnten?

---------

Lieber Anthony

Ich habe noch einen Account registriert, um den Registrationsprozess zu überprüfen.
Die Welcome-Mail sieht immer noch ziemlich unschön aus. Ich habe dir davon a) zwei Screenshots von meinem Handy geschickt (Anhang: IMG) und b) den Text auch noch als weitergeleitetes Mail geschickt (siehe unten).

Ich habe geschaut, ob ich das anpassen kann, und habe den Text bei den Textbausteinen gefunden (siehe InkedScreenshot). Seltsam war, dass der Text dort schon angepasst war (wir hatten ja schon mal drüber gesprochen), aber offenbar von decidim nicht übernommen wurde. Ist also nicht ein "Cache leeren" Problem oder so.

Es gibt einige Punkte, die angepasst werden sollten:

- Absender: "deinKlima" --> deinklima.ch
- Betreff: "Danke, dass du deinklima.chbeigetreten deinklima.ch !" --> "Willkommen bei deinklima.ch"
- Inhalt: So wie in der "Übersetzung" und nicht wie in der "Ursprüngliche Übersetzung". Nach Möglichkeit, dass wir die Übersetzung zukünftig in Decidim selber anpassen können mit dem Term Customizer (obwohl viel besser, finde ich den Text noch nicht optimal, wenn ich mehr Zeit habe, gerne noch überarbeiten).

Ich weiss nicht, wie das geht. Denkst du, es wäre dir möglich, das noch vor dem Vernetzungsanlass anzupassen?
Hoffentlich registrieren sich einige nach dem Anlass und da wäre es schön, wenn die Willkommens-Mail etwas polierter wäre.

Herzliche Grüsse,
David

![IMG_1671](https://user-images.githubusercontent.com/75796635/201494477-e6c79ff6-18d4-459f-9814-e16c82c5ef3a.PNG)
![IMG_1672](https://user-images.githubusercontent.com/75796635/201494478-bd3a45df-c0c3-4cfd-9c41-1e67156b3096.PNG)
![InkedScreenshot 2022-11-12 122327](https://user-images.githubusercontent.com/75796635/201494479-4d5c09a4-f585-46f1-a1f4-e992f737d3e3.jpg)

**Comment by bsantschi** [comment]
Hoi @Kagemaru ich vermute hier einen Zusammenhang mit https://github.com/stadtluzern/decidim-ocl/issues/225, siehst du das auch so? Und falls ja, benötigen wir wiederum die Übersetzung für folgende Keys: https://github.com/stadtluzern/decidim-ocl/issues/225#issuecomment-1270182036 ?

**Comment by innosmith** [comment]
@Kagemaru : bis wann könntest du dieses Ticket lösen? Merci. LG Anthony

**Comment by bsantschi** [comment]
- Bitte Texte von Luzern übernehmen: https://github.com/stadtluzern/decidim-ocl/issues/225#issuecomment-1270182036
- Welcome Notification anpassen
