### ISSUE TITLE
Random Fehler bei Anmeldung

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#38]
Mehrfach hat mir der Kunde bereits berichtet, dass bei der Anmeldung manchmal ein 422 geworfen wird. Oder auch schon ein 403, wenn ich es richtig in Erinnerung habe. Heute ist ein 422 passiert, siehe Screenshot. Datum 22.11.2022, Zeitpunkt 13:23. Könnt ihr bitte in den Logs prüfen, was der Grund sein könnte? Ob dies nur auf INT auftritt, oder auch auf PROD, weiss ich noch nicht.

![anmeldung fehlgeschlagen](https://user-images.githubusercontent.com/75796635/203394988-c73ff140-951a-477c-9e95-f709b232d16a.png)

**Comment by carlobeltrame** [comment]
Hypothese: 
Das einzige was mit basierend auf diesen Informationen einfällt ist folgendes Szenario.
1. Ein User versucht sich einzuloggen, und irgendein Fehler tritt dabei auf (z.B. das falsche Passwort wird eingegeben?)
2. Der User kommt fälschlicherweise auf eine Fehlerseite, welche nicht gleich wieder das Login-Formular enthält
3. Der User klickt auf den Zurück-Button des Browsers um wieder zum (inzwischen leider abgelaufenen) Login-Formular zurück zu kommen
4. Der User gibt das korrekte Passwort ein und sendet das abgelaufene Login-Formular ab
5. Decidim liefert beim Absenden von abgelaufenen Formularen den 422 Fehler
