### ISSUE TITLE
Kontakt E-Mail einrichten

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#46]
Bitte richtet eine E-Mail-Adresse admin@cokreation-winterthur.ch ein. Dieser Account soll als allgemeine Kontaktadresse fungieren und an Nina.Reinmann@win.ch und Marisa.Kappeler@win.ch weiterleiten.

**Comment by bsantschi** [comment]
Verteiler eingerichtet, warte noch auf die Bestätigung, dass es auch wirklich funktioniert hat.

**Comment by bsantschi** [comment]
Bestätigungen Ende Januar erhalten, dass es funktioniert.
