### ISSUE TITLE
Fehlerhafte GID Link im Mail

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#54]
Hashtags in Mails werden nicht als Link, sondern als GID angezeigt

![Bildschirm­foto 2023-04-20 um 16 31 33](https://user-images.githubusercontent.com/60926257/233398447-fcb5bb76-6bbf-434e-9851-81076473fb91.png)

**Comment by bsantschi** [comment]
Hoi Lars, könntest du das bitte auf INT testen?

**Comment by larsUE** [comment]
Funktioniert auf INT wieder, danke!

**Comment by larsUE** [comment]
Zu früh gefreut, ich habe nach wie vor fehlerhafte Hashtags/GID-Darstellung in den Mails, z.B. beim melden eines Beitrags:
<img width="721" alt="Bildschirm­foto 2023-04-24 um 12 19 03" src="https://user-images.githubusercontent.com/60926257/233968863-eacd8a5a-bca5-4b9c-90c5-9cef9366e17e.png">

**Comment by larsUE** [comment]
Der Fehler tritt auch in der User-Activity auf: https://cokreation.winterthur.ch/profiles/lars_kaiser/activity

@Kagemaru: Konntest du dir da bereits was anschauen?

**Comment by carlobeltrame** [comment]
Das sind schlicht Bugs in Decidim. Hashtags in Titeln und Beschreibungen und Kommentaren werden bisher an manchen Orten im UI richtig präsentiert, aber intern wirds in dem GID-Format gespeichert. Standardmässig wird daher überall, wo keine Extra-Logik vorhanden ist, die GID gerendert. Das ist nichts neues, ist z.B. bei den Kommentaren mindestens seit 3 Jahren schon so, soweit ich anhand dem Code verstehe.

Jede Stelle die du hier auflistest müssen wir oder Decidim einzeln fixen. Möchtest du, dass wir damit beginnen?

**Comment by larsUE** [comment]
Ja, gerne beheben im obersten E-Mail und der letzten Aktivität auf der Startseite (siehe hier: https://cokreation.winterthur.ch)

**Comment by larsUE** [comment]
@carlobeltrame : Ich habe noch etwas getestet und sehe die Links nur bei den zwei Fällen. Bitte also diese Cases flicken:

- [ ] Letzte Aktivität auf der Startseite, Beispiel [hier](https://cokreation.winterthur.ch)

![Bildschirm­foto 2023-05-30 um 10 51 55](https://github.com/decidim-swiss/decidim.swiss/assets/60926257/bea87986-a76f-4d7a-ad5b-5a2c02d46d01)

- [ ] E-Mail, dass ein neuer Vorschlag in einem Projekt hinzugefügt wurde, dass ich folge
![Bildschirm­foto 2023-05-30 um 10 53 33](https://github.com/decidim-swiss/decidim.swiss/assets/60926257/57e19c50-002c-4a84-b344-293048b1563e)
 (Beispiel aus Zürich)
 
 Falls dies einfache Fixes sind, dann bitte auch noch die Moderationsansicht (siehe Bild oben flicken). Ansonsten lassen wir es bleiben.

**Comment by Kagemaru** [comment]
> Letzte Aktivität auf der Startseite, Beispiel [hier](https://cokreation.winterthur.ch)
>
Dies scheint ein Problem zu sein, wenn Hashtags im Titel vorkommen. So wie ich das gesehen habe, bricht das an vielen Stellen, weil Decidim dies nicht erwartet.

**Comment by carlobeltrame** [comment]
@Kagemaru dasselbe habe ich in https://github.com/decidim-swiss/decidim.swiss/issues/54#issuecomment-1531563794 auch schon gesagt. Lars möchte das an den zwei ganz spezifischen Stellen gefixt haben.

**Comment by Kagemaru** [comment]
@carlobeltrame Ja danke, den Thread habe ich gelesen.

Ich meinte damit, dass es bei mir an anderen Stellen übel kaputt ist, wenn man einen Link im Titel hat. Ich weiss nur nicht, wie nachhaltig diese Changes sind.
~Aber auf PROD kann ich es nicht reproduzieren. Daher fixe ich es mal.~

Siehe hier:
![Image](https://github.com/decidim-swiss/decidim.swiss/assets/12155/ada1220a-d6b3-453c-8fcd-9b5bdb6797c9)

Edit:

Ich konnte es reproduzieren, mit Änderungsvorschlägen aktiviert:

https://cokreation.winterthur.ch/processes/marktplatz/f/470/proposals/431
![Image](https://github.com/decidim-swiss/decidim.swiss/assets/12155/54463771-7070-4016-bea9-b6f452007b12)

**Comment by Kagemaru** [comment]
Die Fixes sind nun auf INT. Es gibt noch ein seltsames Verhalten mit den Mails, die Follower erhalten. Dort funktioniert es manchmal und manchmal nicht, trotz geleerten Caches.

Laut Lars ist dies vorerst ok so.

**Comment by larsUE** [comment]
Neu entdeckter Case. Da es ein sehr seltenes Mail ist, bitte keine Zeit investieren.

![Image](https://github.com/decidim-swiss/decidim.swiss/assets/60926257/93a99754-5377-4b1f-89ea-c6c164db8915)
