### ISSUE TITLE
Leere Suche führt zu Serverfehler

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#57]
Klickt ein User auf die Suchlupe in der Hauptnavigation, ohne einen Suchparameter mitzugeben, erfolgt eine Server Fehlermeldung siehe Screenshot. 

Auf ImpulsKöniz INT oder DialogLuzern PROD tritt dieser Fehler nicht auf.

![Google Chrome - Serverfehler 2023-05-06 um 11 51 40](https://user-images.githubusercontent.com/75796635/236617028-2fc1dcc3-1cb0-4f79-b9f7-38070a4f2fd1.png)

**Comment by Kagemaru** [comment]
Dies geschieht wegen eines Kommentars, der auf einem gelöschten Meeting besteht. Da Decidim versucht, die ursprüngliche Resource zu laden, kriegt es falsche Daten und crasht.

Soll ich den Kommentar löschen?

**Comment by innosmith** [comment]
Ja, bitte den Kommentar löschen @Kagemaru .
