### ISSUE TITLE
Titelbild anpassbar machen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#58]
Die Kundin möchte das Titelbild auf der Startseite selber ändern können. Das Logo wird dann analog anderer Umsetzungen wie z.B. Dialog Luzern oder MeinQuartier als sep. Layer darüber angezeigt. Welche Umsetzung ist hierfür die Benutzerfreundlichste? Die Umsetzung von Dialog Luzern? Wie genau funktioniert dort der Änderungsprozess?

**Comment by carlobeltrame** [comment]
Das ist ja praktisch bei jedem neuen Tenant wieder die Frage. Ich hatte die verfügbaren Optionen vor ein paar Monaten mal zusammengefasst. Weisst du zufällig gerade noch in welchem Mail oder Issue das war?

**Comment by innosmith** [comment]
> Das ist ja praktisch bei jedem neuen Tenant wieder die Frage. Ich hatte die verfügbaren Optionen vor ein paar Monaten mal zusammengefasst. Weisst du zufällig gerade noch in welchem Mail oder Issue das war?

https://github.com/decidim-swiss/decidim.swiss/issues/52

**Comment by carlobeltrame** [comment]
Mögliche Optionen, von #52 kopiert und ergänzt wie die User spezifisch vorgehen müssen, um das Bild selber anzupassen:


1. Decidim bietet einen Content Block "Hauptbild" den ihr einfach auf die Startseite ziehen und selber ein Bild hochladen könnt. Gestaltungsmöglichkeiten haben wir nur via CSS, also können Farben, Abstände, Schriftgrössen und Schriftarten geändert werden und Elemente entfernt werden, aber keine neuen Elemente hinzugefügt werden.
**Bilder selber hochladen:** ja, einfach via Upload direkt in Decidim an relativ intuitivem Ort
**Höhe bestimmen:** ja, mit CSS
**Logo übers Bild legen:** nein
**Vorteile:** Wenig bis kein Umsetzungsaufwand, intuitives UI um das Bild zu ersetzen
**Nachteile:** Deinklima-Logo kann nicht über das Bild gelegt werden, also müsste das Logo weiterhin direkt auf dem Hintergrundbild drauf sein.

2. Lösung wie bisher. Bild wird wie bei meinquartier.zuerich irgendwo in Decidim hochgeladen (z.B. in einer privaten Organisation oder wie bei Luzern im "Hauptbild"-Block bei den Startseite-Einstellungen) und der korrekte Link (achtung, es gibt jeweils zwei Links, nur einer davon funktioniert dauerhaft) wird im HTML-Block eingetragen.
**Bilder selber hochladen:** ja, einfach via Upload direkt in Decidim, aber an einem nicht intuitiven Ort
**Höhe bestimmen:** ja, mit CSS
**Logo übers Bild legen:** ja, mit einmaligem Entwicklungsaufwand von ca. 0.5 - 1PT
**Vorteile:** Wenig bis kein Umsetzungsaufwand
**Nachteile:** Das Quell-Bild oder die private Organisation etc. könnten aus versehen gelöscht werden, weil der Bezug zur Startseite nicht intuitiv klar ist. Wenn das Bild geändert wird, muss auch daran gedacht werden, den Link zum neuen Bild im HTML-Block zu aktualisieren.

3. Lösung wie bisher. Bild wird auf einem externen Hosting-Service hochgeladen (z.B. vormaliges Metanet-Hosting) und der Link wird im HTML-Block eingetragen.
**Bilder selber hochladen:** ja, aber braucht separaten Zugang zum Hosting, und das Bild muss exakt gleich benannt sein
**Höhe bestimmen:** ja, mit CSS
**Logo übers Bild legen:** ja, mit einmaligem Entwicklungsaufwand von ca. 0.5 - 1PT
**Vorteile:** Wenig bis kein Umsetzungsaufwand
**Nachteile:** Zusätzlicher Zugang für Hosting ist nötig um das Bild zu ändern. Verantwortung und Finanzierung des Hostings müsste geklärt werden. Wenn das Hosting mal nicht oder langsam reagiert, wird auch kein Bild angezeigt (vgl. kürzliche Abklärungen bei meinquartier.zuerich zu langer Karten-Ladezeit von externen Servers).

4. Zusätzlichen Datei-Upload irgendwo in Decidim einprogrammieren (z.B. im System Dashboard oder bei den Einstellungen im Admin Dashboard). Der fix von Decidim generierte Link wird im HTML-Block eingetragen.
**Bilder selber hochladen:** ja, einfach via Upload direkt in Decidim an einem zu definierenden Ort
**Höhe bestimmen:** ja, mit CSS
**Logo übers Bild legen:** ja, mit einmaligem Entwicklungsaufwand von ca. 0.5 - 1PT
**Vorteile:** Intuitives UI um das Bild zu ersetzen
**Nachteile:** Mit Abstand höchster Umsetzungsaufwand (ca. 3PT, genaue Umsetzung noch unklar)

5. Bild in der Codebase einfügen. Der fix generierte Link wird im HTML-Block eingetragen.
**Bilder selber hochladen:** nein, nur via Code-Änderung möglich
**Höhe bestimmen:** ja, mit CSS
**Logo übers Bild legen:** ja, mit einmaligem Entwicklungsaufwand von ca. 0.5 - 1PT
**Vorteile:** User können nichts falsch machen..?
**Nachteile:** Bild ist nicht durch User anpassbar

**Comment by innosmith** [comment]
@carlobeltrame : kannst du bitte prüfen, ob DialogLuzern die gleiche Lösung wie MeinQuartier umgesetzt hat? Merci.

**Comment by carlobeltrame** [comment]
Siehe Beschreibung von Option 2, dort steht es schon.

**Comment by innosmith** [comment]
> Siehe Beschreibung von Option 2, dort steht es schon.

Ok, verstehe. Mit der gleichen Implementierung gibt es 2 Grundoptionen, wo das Bild gespeichert werden kann. Dann bitte die Option 2 für deinklima umsetzen.

**Comment by carlobeltrame** [comment]
Ist gut. Könnt ihr mir dazu das deinklima Logo als Vektorgrafik (SVG oder EPS) zustellen? Dieses habe ich bisher immer nur als Teil des Bildes bekommen.

**Comment by innosmith** [comment]
Anbei das Logo als SVG. Merci.

![deinklima-Logo-Home](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/ba939013-cfeb-4c1e-ad7f-3a7dccd4f143)

**Comment by carlobeltrame** [comment]
@innosmith ich brauche wies aussieht auch noch das Bild selber (ohne das fix draufgemachte Logo). Bis du mir dieses zustellst arbeite ich mal mit dem bisherigen Bild, wo das Logo noch eingebacken ist.

**Comment by innosmith** [comment]
@carlobeltrame : Ich habe das Originalfoto gefunden und Farbfilter angewandt, sodass es der bisherigen Version sehr ähnlich kommt. Bei Bedarf kann ich dir noch den passenden Ausschnitt erstellen, wenn du mir die gewünschte Pixelbreite und -höhe geben kannst.

![Startbild_farblich_geändert](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/8ce8b2ab-44a8-4e8e-887f-03384bb2700f)

**Comment by carlobeltrame** [comment]
Merci. Den Farbfilter könnte ich auch direkt in HTML / CSS realisieren, dann müssen die Kunden nicht jedes Mal vor dem Hochladen daran denken.
Das bisherige Bild ist 2880x1110 Pixel gross, dein Bild ist jetzt noch 2880x1925. Ich könnte das auch mit CSS kompensieren, aber um Bandbreite zu sparen wäre es schon vorteilhaft wenn das hochgeladene Bild bereits zugeschnitten ist.

**Comment by innosmith** [comment]
Passt das angehängte Bild in ungefilterter Form? Wenn du den Filter direkt in HTML/CSS machen kannst, umso besser.

![Startbild_ohne_Logo](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/32c76aa4-3464-4f5c-a945-1cba1183b468)

**Comment by carlobeltrame** [comment]
Habe das umgesetzt. Die WAF hindert mich noch, das Titelbild hochzuladen, habe da Thomas darauf angesetzt. Für den Moment habe ich den Link von hier auf GitHub eingetragen, damit ihr es schon mal anschauen könnt.

**Comment by Kagemaru** [comment]
Das war nicht die WAF, sondern eine Validation, die die Bildgrösse des bereits gespeicherten Bildes überprüft.
Dies verhindert auch das Löschen des bestehenden Bildes.

Das Bild wird anscheinend nicht richtig zugeschnitten beim Hochladen. Ich habe das bestehende Bild nun manuell in der Konsole gelöscht und das neue hochgeladen.

**Comment by carlobeltrame** [comment]
Ticket ist jetzt fertig umgesetzt

**Comment by innosmith** [comment]
@carlobeltrame : ist das bereits auf PROD, wie das Ticket vermuten lässt oder wird dies am Donnerstag deployed?

**Comment by carlobeltrame** [comment]
Ich habe das auf PROD übertragen, gemäss unserer Besprechung am Standup. Ist nur ein HTML-Block plus ein Upload des Titelbilds in den "Hauptbild" Startseiten-Block. Das hat daher kein Code-Deployment benötigt.
