### ISSUE TITLE
Kalenderexport-Button in Veranstaltungsübersicht ausblenden

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#59]
Siehe Screenshot soll in der Veranstaltungsübersicht der Button für den Kalenderexport-Link ausgeblendet werden. Ist dies mit CSS einfach umsetzbar?

![Google Chrome - Veranstaltungen - deinklima ch 2023-05-06 um 11 57 41](https://user-images.githubusercontent.com/75796635/236617511-bb824e59-1cde-490e-b4bd-223f1227b2fe.png)

**Comment by carlobeltrame** [comment]
Ist auf INT umgesetzt

**Comment by innosmith** [comment]
> Ist auf INT umgesetzt

Bestens, ich kopiere den CSS-Block noch auf PROD
