### ISSUE TITLE
Anpassung Veranstaltungsübersicht

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#62]
Wir möchten gerne wissen, wie aufwändig folgende Änderungen wären:

1. Deinklima publiziert nur wenige Veranstaltungen. Wie einfach wäre es, die Filterfunktion auf der linken Seite auszublenden (rein mit CSS möglich?) und dafür mehr Platz für die Veranstaltungen mittig zu erhalten?
2. Immer ALLE Veranstaltungen anzuzeigen, also auch Vergangene?
3. Die Sortierung der Veranstaltungen umzukehren, sodass jeweils die Veranstaltung am weitesten in der Zukunft zuerst erscheint und an letzter Stelle unten rechts die Älteste in der Vergangenheit?

Vermutlich sind für Punkt 2 und 3 tiefergreifende Eingriffe nötig. Müsste dies als eigenes Modul umgesetzt werden, damit die anderen Tenants nicht betroffen sind?

Es ist möglich, dass wenn einmal mehr Veranstaltungen auf deinklima sind, gewisse Anpassungen wieder rückgängig gemacht würden.

**Comment by innosmith** [comment]
Punkt 1 sollte mit CSS möglich sein.
Punkt 2 und 3 Code-Änderung, aber nicht sehr tiefgreifend. Muss Tenant spezifisch gemacht.

**Comment by carlobeltrame** [comment]
Aufwand für Punkte 2 und 3: Je ca. 1-2 Stunden + INT und PROD Deployment. Modul ist dafür nicht nötig, Decidim sieht diese Änderungen ein Stück weit vor und bietet uns relativ schöne Ansatzpunkte um das zu steuern. Allerdings wird wieder eine Code-Änderung nötig sein, wenn das in Zukunft einmal rückgängig gemacht werden soll.

**Comment by innosmith** [comment]
Punkte 2 und 3 umsetzen, die Filter eingeblendet lassen.

**Comment by innosmith** [comment]
Funktioniert wie gewünscht, ready for PROD
