### ISSUE TITLE
Fehler beim Bilderupload

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#64]
Das angehängte Bild kann in einem Textfeld nicht hinzugefügt werden. Der Browser zeigt keine Fehlermeldung an, jedoch eine weisse Seite mit der URL https://test.impulskoeniz.ch/pages/help404. 

![Ansicht LF Park](https://user-images.githubusercontent.com/75796635/236621681-c0874414-a89a-4a44-be25-b80f5037cc0f.jpg)

**Comment by larsUE** [comment]
Hast du die Fehlerseiten bereits erfasst?
Meine Vermutung: Das Bild ist 4000px gross, also zu gross. Das würde einen 413er Fehler auslösen. Da es diese weitergeleitete Seite noch nicht gibt wirst du auf den 404 weitergeleitet, aber diese Seite gibts auch nicht, deshalb erscheint sie blank.

**Comment by innosmith** [comment]
> Hast du die Fehlerseiten bereits erfasst? Meine Vermutung: Das Bild ist 4000px gross, also zu gross. Das würde einen 413er Fehler auslösen. Da es diese weitergeleitete Seite noch nicht gibt wirst du auf den 404 weitergeleitet, aber diese Seite gibts auch nicht, deshalb erscheint sie blank.

Danke für den Tipp Lars. Offenbar werden Bilder grösser 2000px nicht unterstützt. Wir reduzieren entsprechend die Pixelgrösse des Bildes.
