### ISSUE TITLE
Textausrichtung linksbündig bei Umfragen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#65]
Bitte gemäss Bild die verschiedenen Textelemente bei Umfragen linksbündig ausrichten. Das Bsp. stammt aus folgender Umfrage: https://test.impulskoeniz.ch/processes/liebefeldmitte/f/700/.

<img width="448" alt="Bildschirmfoto 2023-05-06 um 13 40 01" src="https://user-images.githubusercontent.com/75796635/236621838-2364b686-c7b4-4787-84e4-db36e6909730.png">

**Comment by carlobeltrame** [comment]
Done auf INT

**Comment by innosmith** [comment]
Bestens, danke @carlobeltrame . Ich kopiere dann das CSS auf PROD.
