### ISSUE TITLE
Anpassungen Projektübersichtskacheln

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#69]
Bitte gemäss Screenshots und Notizen attached die Projektübersichtskacheln informativer machen.

[IK_Anpassung_Projektkachel.pdf](https://github.com/decidim-swiss/decidim.swiss/files/11412293/IK_Anpassung_Projektkachel.pdf)

**Comment by carlobeltrame** [comment]
Ich habe das mal soweit ich konnte auf INT umgesetzt. Das Projekt auf INT hat sich inzwischen verändert, und ich kann nicht mehr 1:1 alle Änderungswünsche nachvollziehen. Bitte auf INT überprüfen und melden, was von jetzt aus noch geändert werden soll.

**Comment by innosmith** [comment]
Ist es einfach möglich, die Projekt- sowie Organisationstitel in den Kacheln Magenta fett zu machen?

Bei der Projektkachel für das Projekt **Liebefeld Mitte** würde nur dieser Text standardmässig fett.
Bei der Organisationskachel für Köniz der Titel **Gemeinde Köniz** fett.

**Comment by carlobeltrame** [comment]
Titel der Kacheln ist jetzt fett.
Bei Liebefeld Mitte wird auf der Kachel der Anfang des Beschreibungstexts angezeigt, und den Teil "Arealentwicklung rund um..." haben die User selber fett gemacht. Willst du dass ich dort jegliche vom User eingefügte Fett-Markierung übersteuere und ausser Kraft setze?

**Comment by innosmith** [comment]
@carlobeltrame : bitte wie von dir vorgeschlagen alle Formatierungen in den Projekt-/Org-Kacheln zum Beschreibungstext übersteuern und normal anzeigen.

**Comment by carlobeltrame** [comment]
Habe die Fett-Markierung übersteuert. Es gibt keine Möglichkeit, sämtliche Formatierungen aufs Mal zu übersteuern. Wenn ihr in Zukunft noch weitere Formatierungen übersteuern möchtet, müssen wir die ebenfalls einzeln abhandeln.

**Comment by innosmith** [comment]
Danke @carlobeltrame. Ready for PROD, resp. CSS machen wir dann vermutlich alles en bloque.
