### ISSUE TITLE
Domain co2neutraleregion.ch durch klimaneutraleregion.ch ersetzen

### ISSUE THREAD

**Issue by bsantschi** [decidim-swiss/decidim.swiss#71]
- [x] Domain co2neutraleregion.ch deaktivieren

- [x] Ziel-URL anpassen. Dazu als Plattform-Admin den URL-Suffix im Decidim Backend ändern von:

bisher https://deinklima.ch/assemblies/co2neutraleregion
neu https://deinklima.ch/assemblies/klimaneutraleregion

- [x] Bruno: E-Mailverteiler erstellen und Weiterleitungen konfigurieren falls Auftraggeberin das wünscht

**Comment by innosmith** [comment]
@Kagemaru bis wann denkst du, die Ziel URL anpassen zu können? Die Kundin möchte gerne rasch die neue URL kommunizieren. Merci!

**Comment by Kagemaru** [comment]
@innosmith Ich habe es gerade umgesetzt. Du kannst nun testen. :smiley:
