### ISSUE TITLE
Intransparentes Icon auf farbigem Hintergrund

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#78]
Siehe Screenshot bitte das Icon auf der Startseite transparent einsetzen anstelle mit weissem Hintergrund. Merci.

![IK_intransparentes_Logo](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/63ebcc27-6f7e-4888-9b76-b2a894bc4b79)

**Comment by carlobeltrame** [comment]
Done auf Integration
