### ISSUE TITLE
Fontanpassungen

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#85]
Bitte die Fonts gemäss Attachments anpassen. Die kommerziellen Schriften sollten nun zur Nutzung auf nachfolgenden Domains freigegeben sein:

- impulskoeniz.ch (Hauptdomain)
- impulsköniz.ch
- impuls-koeniz.ch
- impuls-köniz.ch
- test.impulskoeniz.ch

Die Freischaltung erfolgte durch die Agentur backslash AG. Bei Rückfragen bitte bei mir melden für die Kontaktdaten.

[font-koeniz.txt](https://github.com/decidim-swiss/decidim.swiss/files/11575072/font-koeniz.txt)
![fonts-koeniz](https://github.com/decidim-swiss/decidim.swiss/assets/75796635/da13ba67-2b0f-488f-88a0-2663694f8ff0)

**Comment by carlobeltrame** [comment]
Ist auf Integration umgesetzt. Bitte melden falls noch irgendwo falsche Schriftarten auffallen.

**Comment by innosmith** [comment]
Danke @carlobeltrame. Ist es möglich, den Font auch in automatisch versendeten Emails anzupassen? Falls ja, wie aufwändig würde das umzusetzen?

**Comment by carlobeltrame** [comment]
Erste Einschätzung ohne tief ins Thema einzutauchen: Es wäre vermutlich machbar, aber es würde nicht konsistent bei allen Empfängern gleich aussehen, wäre sehr mühsam bis unmöglich zum testen, und wir hatten in der Vergangenheit immer wieder grosse Probleme mit CSS-Anpassungen in den Mails, wegen Decidim-Problemen und weil Mailclients sehr viel weniger standardisiert sind als Webbrowser.

Den Aufwand schätze ich aufgrund dieser diversen Hürden als unverhältnismässig hoch ein. Wie wichtig ist das den Kunden? Ich vermute dass nur schon die Lösungssuche den kundenseitig gefühlten Aufwand von "dieselben Fonts einfach auch noch auf die Mails anwenden" sprengt.

**Comment by innosmith** [comment]
Danke für die Rückmeldung @carlobeltrame . Ich habe dem Kunden empfohlen, das nicht weiter zu verfolgen.

**Comment by innosmith** [comment]
@carlobeltrame : wir haben hierzu morgen noch ein Meeting. Vermutlich kommen noch ein paar Font-Anpassungswünsche. Ich gebe dir gleich im Anschluss um 15 Uhr Bescheid.

**Comment by innosmith** [comment]
@carlobeltrame : bitte vorerst alles so deployen. Weitere Anpassungen für Schriftgrössen/Abstände erfasse ich in einem sep. Ticket, sobald ready.
