### ISSUE TITLE
Server-Fehler bei Veranstaltungsübersicht Organisation

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#87]
Beim Aufruf der URL:
https://test.deinklima.ch/assemblies/stadtxy/f/778/

erfolgt ein Serverfehler. Es scheint nicht an den einzelnen Veranstaltung zu liegen.

Vermutlich derselbe Fehler tritt bei folgender URL auf:
https://test.deinklima.ch/assemblies/klimaneutraleregion/f/534/

**Comment by carlobeltrame** [comment]
Merci fürs Melden. Das Problem ist ein Folgefehler von der Code-Änderung die @Kagemaru für #62 gemacht hat. @Kagemaru möchtest du das in dem Fall gleich übernehmen? https://sentry.puzzle.ch/pitc/decidim-luzern/issues/62247/

**Comment by bsantschi** [comment]
Ist gemäss Thomas auf INT geflickt.

**Comment by innosmith** [comment]
Danke, ich habe bei kurzen Tests keine Fehler mehr gefunden.
