### ISSUE TITLE
Thomas' Testkommentar auf Prod kann nicht entfernt werden.

### ISSUE THREAD

**Issue by larsUE** [decidim-swiss/decidim.swiss#94]
Ein Testkommentar von Thomas kann nicht entfernt werden (bzw. wurde vom jeweiligen Account selber gelöscht) und erscheint in der «Letzten Aktivität» was etwas unschön ist. Könnt ihr diesen bitte entfernen?

![Image](https://github.com/decidim-swiss/decidim.swiss/assets/60926257/51a164db-c291-4d02-80e6-078588e1f240)

Siehe: https://cokreation.winterthur.ch

**Comment by Kagemaru** [comment]
Ist weg
